### PR TITLE
🚩 Enables use-dev-tty feature in crossterm

### LINKED ISSUE #20: On Mac git hook does not work
The hook ends up with the following output:

```bash
+ exec
+ gimoji --hook .git/COMMIT_EDITMSG
Error: Custom { kind: Other, error: "Failed to initialize input reader" }
```

### PR DESCRIPTION
**Pull request by rimbi**
Fixes #20.

### CODE REVIEW

**Comment by rimbi** [comment]
Can you please test on your linux system @zeenix ?

**Comment by zeenix** [comment]
> Can you please test on your linux system @zeenix ?

Will do now. In the mean time, could you please swap the title and description of the commit message? The commit title is supposed to summarize the change and no the benefits/effects (which could be many), that's for description.

I should add  a contribution guide soon that documents preferred dev practices.

**Review by zeenix — CHANGES_REQUESTED** [review]
Thanks so much for doing this. I can verify that this works on Linux as well. Just update the commit (I took the liberty of adjusting the PR title and description) and we're good to go.

**Comment by rimbi** [comment]
the commit title has been updated.

**Review by zeenix — CHANGES_REQUESTED** [review]
Thanks for updating but since you didn't do it like I suggested, we have redundancy in the title: "Fix #20: Fixes..". The issue ref isn't the most important things about summary of a change. Can you please move it to the description? Thanks.

**Comment by zeenix** [comment]
Then, I'll merge and release.

**Comment by rimbi** [comment]
Maybe you should write whay you expect here and I should update the commit.

**Comment by zeenix** [comment]
> Maybe you should write whay you expect here and I should update the commit.

I did. Apart from [explaining it](https://github.com/zeenix/gimoji/pull/22#issuecomment-1567421803), I also updated the PR title and description so you can just do exactly the same to the commit message. :)

**Comment by zeenix** [comment]
BTW, I [added the contribution guide yesterday](https://github.com/zeenix/gimoji/pull/23) that explains the rationale for my commit nitpicks and suggestions on tools to use to make things easier for folks who are not good with git.

**Comment by zeenix** [comment]
I fixed your commit for you now. Please do have a look. The commit log should have all the details for offline development (think long flights).

**Comment by zeenix** [comment]
@rimbi Hey, I noticed that your name doesn't appear in contributors' list on this project. I think it might be because the email on your commits is not added on your GH account? :thinking:

**Comment by rimbi** [comment]
Hmm yes.

**Pull request merged**
